#!/bin/bash
# NetworkManager dispatcher script to make Ethernet and Wi-Fi mutually exclusive
# Based on example 15 from https://networkmanager.dev/docs/api/latest/nmcli-examples.html
# $1 = interface name, $2 = action (up, down, etc.)

export LC_ALL=C

# Only manage WiFi for Ethernet interface events
[[ ! "$1" =~ ^en ]] && exit 0

enable_disable_wifi ()
{
    result=$(nmcli dev | grep "ethernet" | grep -w "connected")
    if [ -n "$result" ]; then
        nmcli radio wifi off
    else
        nmcli radio wifi on
    fi
}

if [ "$2" = "up" ] || [ "$2" = "down" ]; then
    enable_disable_wifi
fi
