[".config/kitty/config.d/tokyonight"]
  type = "archive"
  url = "https://github.com/folke/tokyonight.nvim/archive/main.tar.gz"
  exact = true
  stripComponents = 3
  refreshPeriod = "168h"
  include = ["*/extras/kitty/*"]

[".config/alacritty/config.d/colors/tokyonight"]
  type = "archive"
  url = "https://github.com/folke/tokyonight.nvim/archive/main.tar.gz"
  exact = true
  stripComponents = 3
  refreshPeriod = "168h"
  include = ["*/extras/alacritty/*"]

[".config/bat/themes"]
  type = "archive"
  url = "https://github.com/folke/tokyonight.nvim/archive/main.tar.gz"
  exact = true
  stripComponents = 3
  refreshPeriod = "168h"
  include = ["*/extras/sublime/*"]

[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/astronvim/astronvim.git"
    refreshPeriod = "24h"
