[".vendor/fzf"]
    type = "archive"
    url = "https://github.com/junegunn/fzf/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"

[".vendor/fasd"]
    type = "archive"
    url = "https://github.com/clvv/fasd/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"

[".vendor/asdf"]
    type = "archive"
    url = "https://github.com/asdf-vm/asdf/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"

[".vendor/tomb"]
    type = "archive"
    url = "https://github.com/dyne/Tomb/archive/refs/tags/v2.9.tar.gz"
    stripComponents = 1

[".vendor/clipster"]
    type = "archive"
    url = "https://github.com/mrichar1/clipster/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"

[".vendor/gruvbox-contrib"]
    type = "archive"
    url = "https://github.com/gruvbox-community/gruvbox-contrib/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"

[".vendor/gogh"]
    type = "archive"
    url = "https://github.com/Mayccoll/Gogh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"

