[".externals/kitty/tokyonight"]
  type = "archive"
  url = "https://github.com/folke/tokyonight.nvim/archive/main.tar.gz"
  exact = true
  stripComponents = 3
  refreshPeriod = "168h"
  include = ["*/extras/kitty/*.conf"]

[".externals/kitty/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/kitty/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/themes", "*/themes/*.conf"]

[".externals/alacritty/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/alacritty/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/catppuccin-*.yml"]

[".externals/neomutt/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/neomutt/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/neomuttrc"]

[".externals/bat/themes/tokyonight"]
  type = "archive"
  url = "https://github.com/folke/tokyonight.nvim/archive/main.tar.gz"
  exact = true
  stripComponents = 3
  refreshPeriod = "168h"
  include = ["*/extras/sublime/*"]

[".externals/bat/themes/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/Catppuccin-*.tmTheme"]

[".externals/btop/themes/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/btop/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["*/themes/*.theme"]

[".externals/tmux/tokyonight"]
  type = "archive"
  url = "https://github.com/folke/tokyonight.nvim/archive/main.tar.gz"
  exact = true
  stripComponents = 3
  refreshPeriod = "168h"
  include = ["*/extras/tmux/*"]

[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/azmodude/lazyvim"
  refreshPeriod = "24h"
  [".config/nvim".pull]
    args = ["--depth", "1"]

[".externals/zsh-syntax-highlighting/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/zsh-syntax-highlighting/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["*/themes/*"]

[".externals/lazygit/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/lazygit/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["*/themes/*"]

[".externals/mako/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/mako/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["*/src/*"]

[".externals/i3/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/i3/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["*/themes/*"]

[".externals/zellij/themes"]
  type = "archive"
  url = "https://github.com/zellij-org/zellij/archive/main.tar.gz"
  exact = true
  stripComponents = 3
  refreshPeriod = "168h"
  include = ["*/example/themes/*"]

[".externals/zgenom"]
    type = "git-repo"
    url = "https://github.com/jandamm/zgenom.git"
    refreshPeriod = "168h"

{{ if ne .chezmoi.os "darwin" }}
{{ $tombVersion := "2.9" }}
[".externals/bin/tomb"]
  type = "file"
  url = "https://github.com/dyne/Tomb/archive/refs/tags/v{{ $tombVersion }}.tar.gz"
  executable = true
  [".externals/bin/tomb".filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "Tomb-{{ $tombVersion }}/tomb"]

{{ $atuinVersion := "14.0.1" }}
[".externals/atuin"]
  type = "archive"
  url = "https://github.com/ellie/atuin/releases/download/v{{ $atuinVersion }}/atuin-v{{ $atuinVersion }}-x86_64-unknown-{{ .chezmoi.os }}-gnu.tar.gz"
  exact = true
  stripComponents = 1
  include = ["*/atuin", "*/completions", "*/completions/*"]

{{ $vividVersion := "0.9.0" }}
[".externals/bin/vivid"]
  type = "file"
  url = "https://github.com/sharkdp/vivid/releases/download/v{{ $vividVersion }}/vivid-v{{ $vividVersion }}-x86_64-unknown-{{ .chezmoi.os }}-gnu.tar.gz"
  exact = true
  executable = true
  [".externals/bin/vivid".filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "vivid-v{{ $vividVersion }}-x86_64-unknown-{{ .chezmoi.os }}-gnu/vivid"]

{{ $cosignVersion := "2.0.1" }}
[".externals/bin/cosign"]
    type = "file"
    url = "https://github.com/sigstore/cosign/releases/download/v{{ $cosignVersion }}/cosign-{{ .chezmoi.os }}-amd64"
    executable = true
{{ end }}
