[".externals/kitty/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/kitty/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/*.conf"]

[".externals/alacritty/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/alacritty/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/catppuccin-*.yml"]

[".externals/bat/themes/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/bat/archive/main.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
  include = ["*/Catppuccin-*.tmTheme"]

[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/astronvim/astronvim.git"
    refreshPeriod = "24h"

[".externals/zsh-syntax-highlighting/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/zsh-syntax-highlighting/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["*/themes/*"]

[".externals/lazygit/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/lazygit/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["*/themes/*"]

[".externals/mako/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/mako/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["*/src/*"]

[".externals/i3/catppuccin"]
  type = "archive"
  url = "https://github.com/catppuccin/i3/archive/main.tar.gz"
  exact = true
  stripComponents = 2
  refreshPeriod = "168h"
  include = ["*/themes/*"]

[".externals/zellij/themes"]
  type = "archive"
  url = "https://github.com/zellij-org/zellij/archive/main.tar.gz"
  exact = true
  stripComponents = 3
  refreshPeriod = "168h"
  include = ["*/example/themes/*"]

