-- Hyprland compositor config (native Lua, 0.55+)
require("confd/10-env")
require("confd/20-input")
require("confd/30-appearance")
require("confd/40-windowrules")
require("confd/45-layerrules")
require("confd/50-keybinds")
require("confd/60-monitors")
require("confd/90-autostart")
