# Static binaries
[".local/bin/mise"]
  type = "file"
  url = "https://github.com/jdx/mise/releases/download/v2025.10.11/mise-v2025.10.11-linux-x64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "mise/bin/mise"]
  refreshPeriod = "168h"

[".local/bin/starship"]
  type = "file"
  url = "https://github.com/starship/starship/releases/download/v1.23.0/starship-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "starship"]
  refreshPeriod = "168h"

[".local/bin/fastfetch"]
  type = "file"
  url = "https://github.com/fastfetch-cli/fastfetch/releases/download/2.54.0/fastfetch-linux-amd64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "fastfetch-linux-amd64/usr/bin/fastfetch"]
  refreshPeriod = "168h"

[".local/bin/vivid"]
  type = "file"
  url = "https://github.com/sharkdp/vivid/releases/download/v0.10.1/vivid-v0.10.1-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "vivid-v0.10.1-x86_64-unknown-linux-musl/vivid"]
  refreshPeriod = "168h"

[".local/bin/zellij"]
  type = "file"
  url = "https://github.com/zellij-org/zellij/releases/download/v0.43.1/zellij-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "zellij"]
  refreshPeriod = "168h"

[".local/bin/topgrade"]
  type = "file"
  url = "https://github.com/topgrade-rs/topgrade/releases/download/v16.0.4/topgrade-v16.0.4-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "topgrade"]
  refreshPeriod = "168h"

[".local/bin/eza"]
  type = "file"
  url = "https://github.com/eza-community/eza/releases/download/v0.23.4/eza_x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "./eza"]
  refreshPeriod = "168h"

[".local/bin/atuin"]
  type = "file"
  url = "https://github.com/atuinsh/atuin/releases/download/v18.8.0/atuin-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "atuin-x86_64-unknown-linux-musl/atuin"]
  refreshPeriod = "168h"

[".local/bin/lazygit"]
  type = "file"
  url = "https://github.com/jesseduffield/lazygit/releases/download/v0.55.1/lazygit_0.55.1_linux_x86_64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lazygit"]
  refreshPeriod = "168h"

[".local/bin/lazydocker"]
  type = "file"
  url = "https://github.com/jesseduffield/lazydocker/releases/download/v0.24.1/lazydocker_0.24.1_Linux_x86_64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lazydocker"]
  refreshPeriod = "168h"

[".local/bin/gh"]
  type = "file"
  url = "https://github.com/cli/cli/releases/download/v2.82.0/gh_2.82.0_linux_amd64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "gh_2.82.0_linux_amd64/bin/gh"]
  refreshPeriod = "168h"

# bat-extras - bash scripts
[".local/bin/batdiff"]
  type = "file"
  url = "https://github.com/eth-p/bat-extras/archive/refs/tags/v2024.08.24.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-extras-2024.08.24/src/batdiff.sh"]
  refreshPeriod = "168h"

[".local/bin/batgrep"]
  type = "file"
  url = "https://github.com/eth-p/bat-extras/archive/refs/tags/v2024.08.24.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-extras-2024.08.24/src/batgrep.sh"]
  refreshPeriod = "168h"

[".local/bin/batman"]
  type = "file"
  url = "https://github.com/eth-p/bat-extras/archive/refs/tags/v2024.08.24.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-extras-2024.08.24/src/batman.sh"]
  refreshPeriod = "168h"

[".local/bin/batwatch"]
  type = "file"
  url = "https://github.com/eth-p/bat-extras/archive/refs/tags/v2024.08.24.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-extras-2024.08.24/src/batwatch.sh"]
  refreshPeriod = "168h"

[".local/bin/prettybat"]
  type = "file"
  url = "https://github.com/eth-p/bat-extras/archive/refs/tags/v2024.08.24.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-extras-2024.08.24/src/prettybat.sh"]
  refreshPeriod = "168h"

[".local/bin/difft"]
  type = "file"
  url = "https://github.com/Wilfred/difftastic/releases/download/0.65.0/difft-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "difft"]
  refreshPeriod = "168h"

[".local/bin/yazi"]
  type = "archive-file"
  url = "https://github.com/sxyazi/yazi/releases/download/v25.5.31/yazi-x86_64-unknown-linux-musl.zip"
  executable = true
  path = "yazi-x86_64-unknown-linux-musl/yazi"
  refreshPeriod = "168h"

[".local/bin/ya"]
  type = "archive-file"
  url = "https://github.com/sxyazi/yazi/releases/download/v25.5.31/yazi-x86_64-unknown-linux-musl.zip"
  executable = true
  path = "yazi-x86_64-unknown-linux-musl/ya"
  refreshPeriod = "168h"
