{{- $versions := .versions -}}
{{- $batExtrasVersion := index $versions "bat-extras" -}}
# Static binaries
[".local/bin/mise"]
  type = "file"
  url = "https://github.com/jdx/mise/releases/download/v{{ $versions.mise }}/mise-v{{ $versions.mise }}-linux-x64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "mise/bin/mise"]
  refreshPeriod = "168h"

[".local/bin/starship"]
  type = "file"
  url = "https://github.com/starship/starship/releases/download/v{{ $versions.starship }}/starship-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "starship"]
  refreshPeriod = "168h"

[".local/bin/fastfetch"]
  type = "file"
  url = "https://github.com/fastfetch-cli/fastfetch/releases/download/{{ $versions.fastfetch }}/fastfetch-linux-amd64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "fastfetch-linux-amd64/usr/bin/fastfetch"]
  refreshPeriod = "168h"

[".local/bin/vivid"]
  type = "file"
  url = "https://github.com/sharkdp/vivid/releases/download/v{{ $versions.vivid }}/vivid-v{{ $versions.vivid }}-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "vivid-v{{ $versions.vivid }}-x86_64-unknown-linux-musl/vivid"]
  refreshPeriod = "168h"

[".local/bin/zellij"]
  type = "file"
  url = "https://github.com/zellij-org/zellij/releases/download/v{{ $versions.zellij }}/zellij-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "zellij"]
  refreshPeriod = "168h"

[".local/bin/topgrade"]
  type = "file"
  url = "https://github.com/topgrade-rs/topgrade/releases/download/v{{ $versions.topgrade }}/topgrade-v{{ $versions.topgrade }}-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "topgrade"]
  refreshPeriod = "168h"

[".local/bin/eza"]
  type = "file"
  url = "https://github.com/eza-community/eza/releases/download/v{{ $versions.eza }}/eza_x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "./eza"]
  refreshPeriod = "168h"

[".local/bin/atuin"]
  type = "file"
  url = "https://github.com/atuinsh/atuin/releases/download/v{{ $versions.atuin }}/atuin-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "atuin-x86_64-unknown-linux-musl/atuin"]
  refreshPeriod = "168h"

[".local/bin/lazygit"]
  type = "file"
  url = "https://github.com/jesseduffield/lazygit/releases/download/v{{ $versions.lazygit }}/lazygit_{{ $versions.lazygit }}_linux_x86_64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lazygit"]
  refreshPeriod = "168h"

[".local/bin/lazydocker"]
  type = "file"
  url = "https://github.com/jesseduffield/lazydocker/releases/download/v{{ $versions.lazydocker }}/lazydocker_{{ $versions.lazydocker }}_Linux_x86_64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lazydocker"]
  refreshPeriod = "168h"

[".local/bin/gh"]
  type = "file"
  url = "https://github.com/cli/cli/releases/download/v{{ $versions.gh }}/gh_{{ $versions.gh }}_linux_amd64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "gh_{{ $versions.gh }}_linux_amd64/bin/gh"]
  refreshPeriod = "168h"

# bat-extras - bash scripts
[".local/bin/batdiff"]
  type = "file"
  url = "https://github.com/eth-p/bat-extras/archive/refs/tags/v{{ $batExtrasVersion }}.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-extras-{{ $batExtrasVersion }}/src/batdiff.sh"]
  refreshPeriod = "168h"

[".local/bin/batgrep"]
  type = "file"
  url = "https://github.com/eth-p/bat-extras/archive/refs/tags/v{{ $batExtrasVersion }}.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-extras-{{ $batExtrasVersion }}/src/batgrep.sh"]
  refreshPeriod = "168h"

[".local/bin/batman"]
  type = "file"
  url = "https://github.com/eth-p/bat-extras/archive/refs/tags/v{{ $batExtrasVersion }}.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-extras-{{ $batExtrasVersion }}/src/batman.sh"]
  refreshPeriod = "168h"

[".local/bin/batwatch"]
  type = "file"
  url = "https://github.com/eth-p/bat-extras/archive/refs/tags/v{{ $batExtrasVersion }}.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-extras-{{ $batExtrasVersion }}/src/batwatch.sh"]
  refreshPeriod = "168h"

[".local/bin/prettybat"]
  type = "file"
  url = "https://github.com/eth-p/bat-extras/archive/refs/tags/v{{ $batExtrasVersion }}.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "bat-extras-{{ $batExtrasVersion }}/src/prettybat.sh"]
  refreshPeriod = "168h"

[".local/bin/difft"]
  type = "file"
  url = "https://github.com/Wilfred/difftastic/releases/download/{{ $versions.difft }}/difft-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "difft"]
  refreshPeriod = "168h"

[".local/bin/yazi"]
  type = "archive-file"
  url = "https://github.com/sxyazi/yazi/releases/download/v{{ $versions.yazi }}/yazi-x86_64-unknown-linux-musl.zip"
  executable = true
  path = "yazi-x86_64-unknown-linux-musl/yazi"
  refreshPeriod = "168h"

[".local/bin/ya"]
  type = "archive-file"
  url = "https://github.com/sxyazi/yazi/releases/download/v{{ $versions.yazi }}/yazi-x86_64-unknown-linux-musl.zip"
  executable = true
  path = "yazi-x86_64-unknown-linux-musl/ya"
  refreshPeriod = "168h"

[".local/bin/cliphist"]
  type = "file"
  url = "https://github.com/sentriz/cliphist/releases/download/v{{ $versions.cliphist }}/v{{ $versions.cliphist }}-linux-amd64"
  executable = true
  refreshPeriod = "168h"

[".local/bin/mani"]
  type = "file"
  url = "https://github.com/alajmo/mani/releases/download/v{{ $versions.mani }}/mani_{{ $versions.mani }}_linux_amd64.tar.gz"
  executable = true
  filter.command = "tar"
  filter.args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "mani"]
  refreshPeriod = "168h"
