# Editor and IDE configurations
[".config/nvim"]
  type = "git-repo"
  url = "https://github.com/gorschu/lazyvim.git"
  branch = "azmo"
  refreshPeriod = "24h"
  # [".config/nvim".pull]
  #     args = ["--depth", "1"]
