---
# Ansible playbook for traditional Fedora Workstation setup
# Mirrors the blue-build Silverblue configuration
#
# Usage: ansible-playbook local.yml --ask-become-pass
# Usage (specific roles): ansible-playbook local.yml --tags base,multimedia -K

- name: Configure Fedora Workstation
  hosts: localhost
  connection: local

  roles:
    - role: networking
      tags: [networking, tailscale]
      vars:
        networking_tailscale_oauth_client_id: "{{ vault_tailscale_oauth[hostname].client_id }}"
        networking_tailscale_oauth_client_secret: "{{ vault_tailscale_oauth[hostname].client_secret }}"
    - role: base
      tags: [base, repos]
    - role: virtualization
      tags: [virtualization, incus]
    - role: multimedia
      tags: [multimedia, codecs]
    - role: desktop
      tags: [desktop, gui]
    - role: hyprland
      tags: [hyprland, wayland]
# vim: set ft=yaml.ansible:
