# Shell plugins and utilities
[".externals/yazi/flavors"]
  type = "git-repo"
  url = "https://github.com/yazi-rs/flavors.git"
  refreshPeriod = "168h"

[".externals/yazi/plugins"]
  type = "git-repo"
  url = "https://github.com/yazi-rs/plugins.git"
  refreshPeriod = "168h"

[".zsh/.antidote"]
    type = "git-repo"
    url = "https://github.com/mattmc3/antidote.git"
    refreshPeriod = "168h"

[".zsh/fzf-git.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf-git.sh/refs/heads/main/fzf-git.sh"
  refreshPeriod = "168h"

[".config/fontconfig/conf.avail/10-nerd-font-symbols.conf"]
  type = "file"
  url = "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/refs/heads/master/10-nerd-font-symbols.conf"
  refreshPeriod = "168h"
