#!/bin/bash

JOBS=0
# get all queues
for queue in $(lpstat -e); do
    # check queues for processing jobs
    QUEUE_JOBS=$(lpstat -l -o $queue | egrep "^[A-Za-z0-9]" | wc -l);
    # add those to total
    let JOBS=${JOBS}+${QUEUE_JOBS}
done
# if we don't have any jobs at all, exit
[[ ${JOBS} -eq 0 ]] && exit 1
# else print out the number of jobs to display
echo ${JOBS}

