---
# Per-host feature flags and configuration
hosts:
  artemis:
    has_mail: true
    has_pim: true
    is_laptop: false
    flatpak:
      apps:
        - com.valvesoftware.Steam
        - net.davidotek.pupgui2
        - com.usebottles.bottles
        - com.discordapp.Discord
        - runtime/org.freedesktop.Platform.VulkanLayer.vkBasalt/x86_64/25.08
        - runtime/org.freedesktop.Platform.VulkanLayer.gamescope/x86_64/25.08
        - runtime/org.freedesktop.Platform.VulkanLayer.MangoHud/x86_64/25.08
  apollo:
    has_mail: true
    has_pim: true
    is_laptop: true
  hephaestus:
    has_mail: true
    has_pim: true
    is_laptop: true
