services:
  systemd:
    mask:
      - gcr-ssh-agent.socket
      - gcr-ssh-agent.service
      - app-org.kde.xwaylandvideobridge@autostart.service
    start_only: []
    enable_restart:
    enable_start:
      - systemd-tmpfiles-setup.service
      - app-com.mitchellh.ghostty.service
      - podman.socket
      - podman-auto-update.timer
      - homebrew.vdirsyncer.timer
      - mail-sync.timer
      - rclone-mount@gdrive.service
      - rclone-mount@dropbox.service
