#!/bin/bash

if ! command -v -p kwriteconfig5 > /dev/null; then
    [[ -e $XDG_CONFIG_HOME/kdeglobals ]] && cat $XDG_CONFIG_HOME/kdeglobals
    exit 0
fi

# Global Settings
kwriteconfig5 --file kdeglobals --group KDE --key "LookAndFeelPackage" "org.kde.breezetwilight.desktop"
kwriteconfig5 --file kdeglobals --group KDE --key "SingleClick" "false"

# Fonts
kwriteconfig5 --file kdeglobals --group General --key "XftHintStyle" "hintslight"
kwriteconfig5 --file kdeglobals --group General --key "XftSubPixel" "rgb"
kwriteconfig5 --file kdeglobals --group General --key "font" "Inter,10,-1,5,50,0,0,0,0,0"
kwriteconfig5 --file kdeglobals --group General --key "menuFont" "Inter,10,-1,5,50,0,0,0,0,0"
kwriteconfig5 --file kdeglobals --group General --key "smallestReadableFont" "Inter,9,-1,5,50,0,0,0,0,0"
kwriteconfig5 --file kdeglobals --group General --key "toolBarFont" "Inter,10,-1,5,50,0,0,0,0,0"
kwriteconfig5 --file kdeglobals --group General --key "fixed" "Iosevka Aile,10,-1,5,50,0,0,0,0,0"
kwriteconfig5 --file kdeglobals --group WM --key "WM" --key "activeFont" "Inter,10,-1,5,57,0,0,0,0,0,Medium"

cat $XDG_CONFIG_HOME/kdeglobals
