#!/bin/bash

# Breeze
kwriteconfig5 --file breezerc --group Style --key "ScrollBarAddLineButtons" 1
kwriteconfig5 --file breezerc --group Style --key "ScrollBarSubLineButtons" 1
kwriteconfig5 --file breezerc --group Windeco --key "ButtonSize" "ButtonSmall"

cat $XDG_CONFIG_HOME/breezerc
