#!/bin/bash

if ! command -v -p kwriteconfig5 > /dev/null; then
    [[ -e $XDG_CONFIG_HOME/kscreenlockerrc ]] && cat $XDG_CONFIG_HOME/kscreenlockerrc
    exit 0
fi


kwriteconfig5 --file kscreenlockerrc --group "Daemon" --key "LockGrace" "10"
kwriteconfig5 --file kscreenlockerrc --group "Daemon" --key "Timeout" "10"

cat "$XDG_CONFIG_HOME/kscreenlockerrc"
