#!/bin/bash

if ! command -v -p kwriteconfig5 > /dev/null; then
    [[ -e $XDG_CONFIG_HOME/powerdevilrc ]] && cat $XDG_CONFIG_HOME/powerdevilrc
    exit 0
fi

# powermanagement
kwriteconfig5 --file powerdevilrc --group BatteryManagement --key "BatteryCriticalAction" "1"
kwriteconfig5 --file powerdevilrc --group General --key "pausePlayersOnSuspend" "true"

cat $XDG_CONFIG_HOME/powerdevilrc
