#!/bin/bash

# Keyboard Config
kwriteconfig5 --file kcminputrc --group Keyboard --key "NumLock" 0
kwriteconfig5 --file kcminputrc --group Keyboard --key "RepeatDelay" 250
kwriteconfig5 --file kcminputrc --group Keyboard --key "RepeatRate" 40

cat $XDG_CONFIG_HOME/kcminputrc
