#!/bin/bash

if ! command -v -p kwriteconfig5 >/dev/null || ! command -v -p balooctl >/dev/null; then
  [[ -e $XDG_CONFIG_HOME/baloofilerc ]] && cat "$XDG_CONFIG_HOME/baloofilerc"
  exit 0
fi

# Baloo
# kwriteconfig5 is a bit picky if the file to be modified does not exist
[[ ! -e $XDG_CONFIG_HOME/baloofilerc ]] && echo -e "[General]\nonly basic indexing=true" >$XDG_CONFIG_HOME/baloofilerc
kwriteconfig5 --file baloofilerc --group General --key "only basic indexing" "true"
if ! balooctl config list excludeFolders | grep -q $HOME; then
  balooctl config add excludeFolders $HOME
fi
if ! balooctl config list excludeFolders | grep -q $HOME/mail; then
  balooctl config add includeFolders $HOME/Documents
  balooctl config add includeFolders $HOME/Pictures
  balooctl config add includeFolders $HOME/Videos
  balooctl config add includeFolders $HOME/Calibre
fi

cat $XDG_CONFIG_HOME/baloofilerc
