[aws]
symbol = " "
style = "bold #ffb86c"

[cmd_duration]
style = "bold #f1fa8c"
show_notifications = true
min_time_to_notify = 60_000

[directory]
style = "bold #50fa7b"
read_only = "  "
read_only_style = "#BF616A"
truncation_symbol = "…/"
truncation_length = 3
fish_style_pwd_dir_length = 1

[git_branch]
style = "bold #ff79c6"
symbol = " "

[git_status]
style = "bold #ff5555"
ahead = "⇡${count}"
diverged = "😰⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_metrics]
disabled = false

[git_commit]
disabled = false
tag_disabled = false
only_detached = false

[golang]
symbol = "ﳑ "

[hostname]
style = "bold #ff5555"

[java]
symbol = " "
style = "blue"

[docker_context]
disabled = false
symbol = " "

[line_break]
disabled = true

[package]
symbol = "  "

[shlvl]
disabled = false
symbol = "溜"

[shell]
disabled = false

[status]
disabled = false

[username]
format = "[$user]($style) on "
style_user = "bold #bd93f9"
show_always = true
