[aws]
symbol = " "

[cmd_duration]
style = "#EBCB8B"
show_notifications = true
min_time_to_notify = 60_000

[directory]
read_only = "  "
read_only_style = "#BF616A"
truncation_symbol = "…/"
truncation_length = 3
fish_style_pwd_dir_length = 1

[git_branch]
symbol = " "

[git_status]
ahead = "⇡${count}"
diverged = "😰⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "#81A1C1"

[git_metrics]
disabled = false

[git_commit]
disabled = false
tag_disabled = false
only_detached = false

[golang]
symbol = "ﳑ "

[java]
symbol = " "
style = "blue"

[docker_context]
disabled = false
symbol = " "

[line_break]
disabled = true

[package]
symbol = "  "

[shlvl]
disabled = false
symbol = "溜"

[shell]
disabled = false

[status]
disabled = false
