[gdrive]
type = drive
client_id =
client_secret =
scope = drive
root_folder_id =
fast_list = true
chunk_size = 32M
token = __PRESERVE__

[dropbox]
type = dropbox
fast_list = true
token = __PRESERVE__

[ocis]
type = webdav
url = https://ocis.gobagreven.de/dav/spaces/91df2cf2-8885-4867-b602-475bd599282a$55d90393-9d28-4ce3-a3a1-85bd745e1b5d
vendor = owncloud
user = gorschu
pass =
